---
- name: Setup dan's environment
  hosts: localhost
  become: true
  vars:
    user_name: "dan"
    home_dir: "/home/{{ user_name }}"
    nvim_dir: "{{ home_dir }}/.config/nvim"
    fish_dir: "{{ home_dir }}/.config/fish"
    files_to_upload:
      - src: /files/40-libinput.conf
        dest: /etc/X11/xorg.conf.d/40-libinput.conf
        mode: 644
        owner: root
        group: root
      - src: /files/01-touchpad.conf
        dest: /etc/X11/xorg.conf.d/01-touchpad.conf
        mode: 644
        owner: root
        group: root
      - src: /files/dwmblocks.hook
        dest: /etc/pacman.d/hooks/dwmblocks.hook
        mode: 644
        owner: root
        group: root

  tasks:

    - name: Create user
      user:
        name: "{{ user_name }}"
        createhome: yes
        home: "{{ home_dir }}"

    - name: Install common packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ (lookup('file', 'packages_common.yml') | from_yaml)['packages'] }}"


    - name: Clone neovim config
      git:
        repo: https://github.com/dme86/neovim
        dest: "{{ nvim_dir }}"
        clone: yes
        update: yes
        force: yes
        depth: 1
      become_user: "{{ user_name }}"

    - name: Clone fish config
      git:
        repo: https://github.com/dme86/fish
        dest: "{{ fish_dir }}"
        clone: yes
        update: yes
        force: yes
        depth: 1
      become_user: "{{ user_name }}"

      ### only if --extra-vars "desktop=True"

    - name: Install desktop packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ (lookup('file', 'packages_desktop.yml') | from_yaml)['packages'] }}"
      when: desktop|default(False)|bool

    - name: Clone dwm config
      git:
        repo: https://github.com/dme86/dwm
        dest: "{{ home_dir }}/dwm"
        clone: yes
        update: yes
        force: yes
        depth: 1
      become_user: "{{ user_name }}"
      when: desktop|default(False)|bool

    - name: Clone wallpapers
      git:
        repo: https://github.com/dme86/.wallpapers
        dest: "{{ home_dir }}/.wallpapers"
        clone: yes
        update: yes
        force: yes
        depth: 1
      become_user: "{{ user_name }}"
      when: desktop|default(False)|bool

    - name: Install dwm
      command: make install
      args:
        chdir: "{{ home_dir }}/dwm"
      when: desktop|default(False)|bool

    - name: Install dwmblocks
      shell: |
        cd {{ home_dir }}/dwm/dwmblocks-async
        make dwmblocks
        make install
      when: desktop|default(False)|bool

    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/pacman.d/hooks/
      when: desktop|default(False)|bool

    - name: Ensure HookDir line is uncommented in pacman.conf
      become: true
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#?(HookDir\s+=\s+/etc/pacman\.d/hooks/)$'
        line: '\1'
        backup: yes
      when: desktop|default(False)|bool

    - name: Check if .xinitrc file exists
      stat:
        path: "{{ home_dir }}/.xinitrc"
      register: xinitrc_file

    - name: Create .xinitrc file if it does not exist
      copy:
        content: "exec dwm"
        dest: "{{ home_dir }}/.xinitrc"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: 0644
      when: not xinitrc_file.stat.exists

    - name: Check if files exist on remote machine
      stat:
        path: "{{ item.dest }}"
      with_items: "{{ files_to_upload }}"
      register: file_stat
      when: desktop|default(false)|bool

# TODO: add upload of multiple files
# fix: warning: config file /etc/pacman.conf, line 17: directive '\1' in section 'options' not recognized.
